#define CTYPE_H
int isupper(char);
int islower(char);
int isalpha(char);
int iscntrl(char);
int isdigit(char);
int isalnum(char);
int isspace(char);
int isxdigit(char);
char tolower(char);
char toupper(char);
int isgraph(char);
int isprint(char);
int ispunct(char);